
name: testgen

x-common-variables: &common-variables
  TESTGEN_USERNAME: admin
  TESTGEN_PASSWORD: x8SsArytigOf
  TG_DECRYPT_SALT: HKsYIF8sQGRb
  TG_DECRYPT_PASSWORD: IkPzW6auBkl2
  TG_METADATA_DB_HOST: postgres
  TG_TARGET_DB_TRUST_SERVER_CERTIFICATE: yes
  TG_EXPORT_TO_OBSERVABILITY_VERIFY_SSL: no
  TG_DOCKER_RELEASE_CHECK_ENABLED: yes
  TG_INSTANCE_ID: 6cec47fd9419af3f
  TG_ANALYTICS: yes


services:
  engine:
    image: datakitchen/dataops-testgen:v3
    container_name: testgen
    environment: *common-variables
    volumes:
      - testgen_data:/var/lib/testgen

    ports:
      - 8501:8501
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - postgres
    networks:
      - datakitchen

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=x8SsArytigOf
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 8s
      timeout: 5s
      retries: 3
    networks:
      - datakitchen

volumes:
  postgres_data:
  testgen_data:

networks:
  datakitchen:
    name: datakitchen-network
    external: true
